spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  http:
    encoding:
      charset: UTF-8
      force: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


cloud:
  aws:
    credentials:
      accessKey: AKIAY5ELWLYK2GAGI6CO
      secretKey: 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
    s3:
      bucket: blog-img-store
    region:
      static: ap-northeast-2
    stack:
      auto: false

